"""
routes/ai.py
------------
AI engine endpoints – keyword-based (existing) and LangChain/LangGraph-powered
(new smart endpoints).

Keyword-based (existing):
  GET  /ai/suggest-reply/{ticket_id}          – canned reply suggestions
  POST /ai/classify/{ticket_id}               – classify and update ticket
  POST /ai/prioritize/{ticket_id}             – set priority from content

LangChain/LangGraph-powered (new):
  GET  /ai/suggest-reply-smart/{ticket_id}    – LLM-powered reply suggestions
  POST /ai/classify-smart/{ticket_id}         – LLM-based classification
  POST /ai/process-with-workflow/{ticket_id}  – LangGraph workflow execution
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from database.connection import get_db
from schemas.ticket import TicketOut
from services import ai_service
from services.langchain_ai_service import langchain_ai_service
from services.langgraph_workflow import langgraph_workflow_service
from services.ticket_service import get_ticket_by_id

router = APIRouter(prefix="/ai", tags=["AI Engine"])


@router.get("/suggest-reply/{ticket_id}")
async def suggest_reply(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Return 3 canned reply suggestions for the ticket's content."""
    ticket = await get_ticket_by_id(db, ticket_id)
    if ticket is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ticket not found.")
    content = ""
    if ticket.messages:
        content = ticket.messages[0].content
    elif ticket.subject:
        content = ticket.subject
    channel_str = ticket.channel.value if ticket.channel else None
    suggestions = ai_service.suggest_replies(content, channel_str)
    return {"suggestions": suggestions}


@router.post("/classify/{ticket_id}", response_model=TicketOut)
async def classify_ticket(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> TicketOut:
    """Classify the ticket's priority and category based on message content, then update."""
    from sqlalchemy import select
    from models.ticket import Ticket

    classification = await ai_service.classify_ticket(db, ticket_id)
    if "error" in classification:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=classification["error"])

    result = await db.execute(select(Ticket).where(Ticket.id == ticket_id))
    ticket = result.scalars().first()
    ticket.priority = classification["suggested_priority"]
    ticket.category = classification["suggested_category"]
    await db.commit()
    await db.refresh(ticket)
    return ticket


@router.post("/prioritize/{ticket_id}", response_model=TicketOut)
async def prioritize_ticket(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> TicketOut:
    """Update only the priority of a ticket based on message content analysis."""
    from sqlalchemy import select
    from models.ticket import Ticket

    classification = await ai_service.classify_ticket(db, ticket_id)
    if "error" in classification:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=classification["error"])

    result = await db.execute(select(Ticket).where(Ticket.id == ticket_id))
    ticket = result.scalars().first()
    ticket.priority = classification["suggested_priority"]
    await db.commit()
    await db.refresh(ticket)
    return ticket


# ---------------------------------------------------------------------------
# LangChain / LangGraph-powered endpoints (new)
# ---------------------------------------------------------------------------

@router.get("/suggest-reply-smart/{ticket_id}")
async def suggest_reply_smart(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """
    Return contextually-relevant reply suggestions generated by a LangChain
    chain backed by GPT-4.

    Falls back to keyword-based suggestions automatically when OpenAI is
    unavailable.  The ``powered_by`` field in the response indicates which
    path was used (``langchain`` or ``keyword_fallback``).
    """
    result = await langchain_ai_service.suggest_replies_smart(db, ticket_id)
    if "error" in result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=result["error"]
        )
    return result


@router.post("/classify-smart/{ticket_id}")
async def classify_ticket_smart(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """
    Classify a ticket's priority, category, department, and routing using a
    LangChain chain backed by GPT-4.

    Falls back to keyword-based classification when OpenAI is unavailable.
    The ``powered_by`` field in the response indicates which path was used.
    """
    result = await langchain_ai_service.classify_ticket_smart(db, ticket_id)
    if "error" in result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=result["error"]
        )
    return result


@router.post("/process-with-workflow/{ticket_id}")
async def process_with_workflow(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """
    Process a ticket through the full LangGraph multi-step workflow.

    The workflow runs four nodes in sequence:
      1. classify – LLM-based priority / category / department
      2. decide_response – auto-respond vs. escalate decision
      3. route_agent – routing reason and department assignment
      4. human_review – flag for human oversight if needed

    Falls back to keyword-based processing when LangGraph is unavailable.
    The ``powered_by`` field indicates which path was used.
    """
    result = await langgraph_workflow_service.process_ticket(db, ticket_id)
    if "error" in result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=result["error"]
        )
    return result
